# Generated by Django 5.2.11 on 2026-02-16 11:47

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(default=apps.orders.models.generate_order_no, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED')], default='PENDING', max_length=24)),
                ('subtotal_amount', models.PositiveIntegerField(default=0)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('recipient', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('road_address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('READY', 'READY'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED'), ('FAILED', 'FAILED')], default='UNPAID', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.PositiveIntegerField()),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('option_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
                ('product_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productoption')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
