# Generated by Django 5.2.11 on 2026-02-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('READY', 'READY'), ('PREPARING', 'PREPARING'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default='READY', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
