# Generated by Django 5.2.11 on 2026-02-17 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_courier_name_order_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('APPROVED', 'APPROVED'), ('PICKUP_SCHEDULED', 'PICKUP_SCHEDULED'), ('RECEIVED', 'RECEIVED'), ('REFUNDING', 'REFUNDING'), ('REFUNDED', 'REFUNDED'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED')], default='REQUESTED', max_length=24)),
                ('reason_title', models.CharField(max_length=200)),
                ('reason_detail', models.TextField(blank=True)),
                ('requested_amount', models.PositiveIntegerField(default=0)),
                ('approved_amount', models.PositiveIntegerField(default=0)),
                ('rejected_reason', models.TextField(blank=True)),
                ('pickup_courier_name', models.CharField(blank=True, max_length=100)),
                ('pickup_tracking_no', models.CharField(blank=True, max_length=100)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('SCHEDULED', 'SCHEDULED'), ('PAID', 'PAID')], default='PENDING', max_length=20)),
                ('gross_amount', models.IntegerField(default=0)),
                ('discount_amount', models.IntegerField(default=0)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('pg_fee', models.IntegerField(default=0)),
                ('platform_fee', models.IntegerField(default=0)),
                ('return_deduction', models.IntegerField(default=0)),
                ('settlement_amount', models.IntegerField(default=0)),
                ('expected_payout_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_record', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
