# Generated by Django 5.2.11 on 2026-02-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_returnrequest_settlementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_provider',
            field=models.CharField(choices=[('NONE', 'NONE'), ('CJ', 'CJ'), ('HANJIN', 'HANJIN'), ('LOTTE', 'LOTTE'), ('EPOST', 'EPOST')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_sync_status',
            field=models.CharField(choices=[('NOT_CONNECTED', 'NOT_CONNECTED'), ('READY', 'READY'), ('SYNCED', 'SYNCED'), ('FAILED', 'FAILED')], default='NOT_CONNECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('DIRECT', 'DIRECT'), ('NAVER_PAY', 'NAVER_PAY'), ('MARKETPLACE', 'MARKETPLACE')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='external_settlement_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='settlement_last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='settlement_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='settlement_provider',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('NAVER_PAY', 'NAVER_PAY')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='settlement_sync_status',
            field=models.CharField(choices=[('NOT_CONNECTED', 'NOT_CONNECTED'), ('READY', 'READY'), ('SYNCED', 'SYNCED'), ('FAILED', 'FAILED')], default='NOT_CONNECTED', max_length=20),
        ),
    ]
