# Generated by Django 5.2.11 on 2026-02-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_external_order_id_order_logistics_last_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_last_error',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_last_synced_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_sync_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='external_settlement_id',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='settlement_last_error',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='settlement_last_synced_at',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='settlement_provider',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='settlement_sync_status',
        ),
    ]
