# Generated by Django 5.2.11 on 2026-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_external_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jibun_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
