# Generated by Django 5.2.11 on 2026-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_jibun_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_order_status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAYMENT_COMPLETED', 'PAYMENT_COMPLETED'), ('SHIPPING', 'SHIPPING'), ('DELIVERED', 'DELIVERED'), ('PURCHASE_CONFIRMED', 'PURCHASE_CONFIRMED'), ('EXCHANGE', 'EXCHANGE'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED'), ('UNPAID_CANCELED', 'UNPAID_CANCELED')], default='PAYMENT_PENDING', max_length=32),
        ),
    ]
