# Generated by Django 5.2.11 on 2026-02-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_product_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettlementRecord',
        ),
    ]
