# Generated by Django 5.2.11 on 2026-02-17 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deposittransaction_onetooneinquiry_pointtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetooneinquiry',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='category',
            field=models.CharField(choices=[('DELIVERY', 'DELIVERY'), ('RETURN_REFUND', 'RETURN_REFUND'), ('PAYMENT', 'PAYMENT'), ('ORDER', 'ORDER'), ('PRODUCT', 'PRODUCT'), ('ETC', 'ETC')], default='ETC', max_length=30),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='channel',
            field=models.CharField(default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('NORMAL', 'NORMAL'), ('HIGH', 'HIGH'), ('URGENT', 'URGENT')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetooneinquiry',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
