# Generated by Django 5.2.11 on 2026-02-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_admin_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).update(admin_role="SUPER_ADMIN")
    User.objects.filter(is_staff=True, is_superuser=False).update(admin_role="OPS")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_onetooneinquiry_assigned_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('OPS', 'OPS'), ('CS', 'CS'), ('WAREHOUSE', 'WAREHOUSE'), ('FINANCE', 'FINANCE'), ('MARKETING', 'MARKETING'), ('READ_ONLY', 'READ_ONLY')], default='READ_ONLY', max_length=24),
        ),
        migrations.RunPython(set_default_admin_roles, migrations.RunPython.noop),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status_code', models.PositiveIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_role', models.CharField(blank=True, max_length=24)),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], default='SUCCESS', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['occurred_at'], name='accounts_au_occurre_5cdd76_idx'), models.Index(fields=['action', 'occurred_at'], name='accounts_au_action_865072_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx'), models.Index(fields=['actor_admin', 'occurred_at'], name='accounts_au_actor_a_3847d3_idx')],
            },
        ),
    ]
