# Generated by Django 5.2.11 on 2026-02-16 11:47

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('fail_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('NAVERPAY', 'NAVERPAY')], default='NAVERPAY', max_length=20)),
                ('payment_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='READY', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fail_code', models.CharField(blank=True, max_length=100)),
                ('fail_message', models.TextField(blank=True)),
                ('raw_request_json', models.JSONField(blank=True, default=dict)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(default=apps.payments.models.generate_idempotency_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
