# Generated by Django 5.2.11 on 2026-02-17 09:44

import apps.payments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_jibun_address'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('NAVERPAY', 'NAVERPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='NAVERPAY', max_length=20),
        ),
        migrations.CreateModel(
            name='BankTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depositor_name', models.CharField(max_length=100)),
                ('depositor_phone', models.CharField(blank=True, max_length=20)),
                ('transfer_amount', models.PositiveIntegerField(default=0)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=100)),
                ('transfer_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_memo', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(default=apps.payments.models.generate_idempotency_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_requests', to='orders.order')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_bank_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_ba_status_3c5541_idx'), models.Index(fields=['order', 'status'], name='payments_ba_order_i_a5f1bd_idx')],
            },
        ),
    ]
