# Generated by Django 5.2.11 on 2026-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('NAVERPAY', 'NAVERPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
