# Generated by Django 5.2.11 on 2026-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('bank_name', models.CharField(default='신한은행', max_length=100)),
                ('bank_account_no', models.CharField(default='110-555-012345', max_length=50)),
                ('account_holder', models.CharField(default='소살리토', max_length=100)),
                ('guide_message', models.CharField(default='입금 후 관리자 확인이 완료되면 결제완료 처리됩니다.', max_length=255)),
                ('verification_notice', models.CharField(default='입금자명은 주문자명과 동일하게 입력해 주세요.', max_length=255)),
                ('cash_receipt_guide', models.CharField(default='결제완료 후 마이페이지 또는 고객센터에서 현금영수증 발급을 요청할 수 있습니다.', max_length=255)),
                ('business_name', models.CharField(default='주식회사 네로', max_length=150)),
                ('business_ceo_name', models.CharField(blank=True, default='', max_length=120)),
                ('business_no', models.CharField(default='123-45-67890', max_length=40)),
                ('ecommerce_no', models.CharField(default='2026-서울마포-0001', max_length=80)),
                ('business_address', models.CharField(blank=True, default='', max_length=255)),
                ('support_phone', models.CharField(default='1588-1234', max_length=60)),
                ('support_email', models.CharField(default='cs@nero.ai.kr', max_length=120)),
                ('support_hours', models.CharField(default='평일 10:00 - 18:00 / 점심 12:30 - 13:30', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Transfer Account Config',
                'verbose_name_plural': 'Bank Transfer Account Config',
                'ordering': ['id'],
            },
        ),
    ]
