from django.urls import path

from .admin_views import (
    AdminHomeBannerDetailAPIView,
    AdminHomeBannerListCreateAPIView,
    AdminProductDetailAPIView,
    AdminProductListCreateAPIView,
    AdminProductMetaAPIView,
    AdminCouponDetailAPIView,
    AdminCouponListCreateAPIView,
    AdminDashboardAPIView,
    AdminInquiryAnswerAPIView,
    AdminInquiryListAPIView,
    AdminOrderListAPIView,
    AdminOrderUpdateAPIView,
    AdminReturnRequestListCreateAPIView,
    AdminReturnRequestUpdateAPIView,
    AdminReviewDeleteAPIView,
    AdminReviewListAPIView,
    AdminReviewVisibilityAPIView,
    AdminStaffUserListAPIView,
    AdminSettlementListGenerateAPIView,
    AdminSettlementUpdateAPIView,
    AdminUserDetailAPIView,
    AdminUserListAPIView,
)
from .views import (
    HealthCheckAPIView,
    InquiryListCreateAPIView,
    KakaoCallbackAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    MyPageDashboardAPIView,
    PasswordChangeAPIView,
    RecentViewedProductAPIView,
    RefreshAPIView,
    WishlistAPIView,
    WishlistDetailAPIView,
)

urlpatterns = [
    path("health/", HealthCheckAPIView.as_view(), name="health-check"),
    path("auth/login", LoginAPIView.as_view(), name="auth-login"),
    path("auth/kakao/callback", KakaoCallbackAPIView.as_view(), name="auth-kakao-callback"),
    path("auth/refresh", RefreshAPIView.as_view(), name="auth-refresh"),
    path("auth/logout", LogoutAPIView.as_view(), name="auth-logout"),
    path("users/me", MeAPIView.as_view(), name="users-me"),
    path("users/me/password", PasswordChangeAPIView.as_view(), name="users-password"),
    path("users/me/dashboard", MyPageDashboardAPIView.as_view(), name="users-dashboard"),
    path("users/me/wishlist", WishlistAPIView.as_view(), name="users-wishlist"),
    path("users/me/wishlist/<int:product_id>", WishlistDetailAPIView.as_view(), name="users-wishlist-detail"),
    path("users/me/recent-products", RecentViewedProductAPIView.as_view(), name="users-recent-products"),
    path("users/me/inquiries", InquiryListCreateAPIView.as_view(), name="users-inquiries"),
    path("admin/dashboard", AdminDashboardAPIView.as_view(), name="admin-dashboard"),
    path("admin/orders", AdminOrderListAPIView.as_view(), name="admin-orders"),
    path("admin/orders/<str:order_no>", AdminOrderUpdateAPIView.as_view(), name="admin-order-update"),
    path("admin/returns", AdminReturnRequestListCreateAPIView.as_view(), name="admin-returns"),
    path("admin/returns/<int:return_request_id>", AdminReturnRequestUpdateAPIView.as_view(), name="admin-return-update"),
    path("admin/settlements", AdminSettlementListGenerateAPIView.as_view(), name="admin-settlements"),
    path("admin/settlements/<int:settlement_id>", AdminSettlementUpdateAPIView.as_view(), name="admin-settlement-update"),
    path("admin/inquiries", AdminInquiryListAPIView.as_view(), name="admin-inquiries"),
    path("admin/inquiries/<int:inquiry_id>/answer", AdminInquiryAnswerAPIView.as_view(), name="admin-inquiry-answer"),
    path("admin/reviews", AdminReviewListAPIView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:review_id>", AdminReviewDeleteAPIView.as_view(), name="admin-review-delete"),
    path("admin/reviews/<int:review_id>/visibility", AdminReviewVisibilityAPIView.as_view(), name="admin-review-visibility"),
    path("admin/banners/home/manage", AdminHomeBannerListCreateAPIView.as_view(), name="admin-banner-manage"),
    path("admin/banners/home/manage/<int:banner_id>", AdminHomeBannerDetailAPIView.as_view(), name="admin-banner-detail"),
    path("admin/products/manage/meta", AdminProductMetaAPIView.as_view(), name="admin-product-meta"),
    path("admin/products/manage", AdminProductListCreateAPIView.as_view(), name="admin-product-manage"),
    path("admin/products/manage/<int:product_id>", AdminProductDetailAPIView.as_view(), name="admin-product-detail"),
    path("admin/users/manage", AdminUserListAPIView.as_view(), name="admin-user-manage"),
    path("admin/users/manage/<int:user_id>", AdminUserDetailAPIView.as_view(), name="admin-user-detail"),
    path("admin/coupons", AdminCouponListCreateAPIView.as_view(), name="admin-coupons"),
    path("admin/coupons/<int:coupon_id>", AdminCouponDetailAPIView.as_view(), name="admin-coupon-delete"),
    path("admin/staff-users", AdminStaffUserListAPIView.as_view(), name="admin-staff-users"),
]
