from django.urls import path

from .admin_views import (
    AdminBrandPageSettingAPIView,
    AdminBrandStorySectionDetailAPIView,
    AdminBrandStorySectionListCreateAPIView,
    AdminHomeBannerDetailAPIView,
    AdminHomeBannerListCreateAPIView,
    AdminProductDetailAPIView,
    AdminProductListCreateAPIView,
    AdminProductMetaAPIView,
    AdminCouponDetailAPIView,
    AdminCouponListCreateAPIView,
    AdminDashboardAPIView,
    AdminAuditLogListAPIView,
    AdminInquiryAnswerAPIView,
    AdminInquiryListAPIView,
    AdminOrderListAPIView,
    AdminOrderUpdateAPIView,
    AdminReturnRequestListCreateAPIView,
    AdminReturnRequestUpdateAPIView,
    AdminReviewDeleteAPIView,
    AdminReviewListAPIView,
    AdminReviewManageAPIView,
    AdminReviewReportManageAPIView,
    AdminReviewVisibilityAPIView,
    AdminStaffUserListAPIView,
    AdminSettlementListGenerateAPIView,
    AdminSettlementUpdateAPIView,
    AdminSupportFaqDetailAPIView,
    AdminSupportFaqListCreateAPIView,
    AdminSupportNoticeDetailAPIView,
    AdminSupportNoticeListCreateAPIView,
    AdminUserDetailAPIView,
    AdminUserListAPIView,
)
from .views import (
    HealthCheckAPIView,
    InquiryListCreateAPIView,
    KakaoAuthorizeUrlAPIView,
    KakaoCallbackAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    MyPageDashboardAPIView,
    PasswordChangeAPIView,
    RecentViewedProductAPIView,
    RegisterAPIView,
    RefreshAPIView,
    PublicInquiryListAPIView,
    SupportFaqListAPIView,
    SupportNoticeListAPIView,
    UserWithdrawAPIView,
    UserDefaultAddressAPIView,
    WishlistAPIView,
    WishlistDetailAPIView,
)

urlpatterns = [
    path("health/", HealthCheckAPIView.as_view(), name="health-check"),
    path("auth/login", LoginAPIView.as_view(), name="auth-login"),
    path("auth/register", RegisterAPIView.as_view(), name="auth-register"),
    path("auth/kakao/authorize-url", KakaoAuthorizeUrlAPIView.as_view(), name="auth-kakao-authorize-url"),
    path("auth/kakao/callback", KakaoCallbackAPIView.as_view(), name="auth-kakao-callback"),
    path("auth/refresh", RefreshAPIView.as_view(), name="auth-refresh"),
    path("auth/logout", LogoutAPIView.as_view(), name="auth-logout"),
    path("users/me", MeAPIView.as_view(), name="users-me"),
    path("users/me/default-address", UserDefaultAddressAPIView.as_view(), name="users-default-address"),
    path("users/me/password", PasswordChangeAPIView.as_view(), name="users-password"),
    path("users/me/withdraw", UserWithdrawAPIView.as_view(), name="users-withdraw"),
    path("users/me/dashboard", MyPageDashboardAPIView.as_view(), name="users-dashboard"),
    path("users/me/wishlist", WishlistAPIView.as_view(), name="users-wishlist"),
    path("users/me/wishlist/<int:product_id>", WishlistDetailAPIView.as_view(), name="users-wishlist-detail"),
    path("users/me/recent-products", RecentViewedProductAPIView.as_view(), name="users-recent-products"),
    path("users/me/inquiries", InquiryListCreateAPIView.as_view(), name="users-inquiries"),
    path("support/notices", SupportNoticeListAPIView.as_view(), name="support-notices"),
    path("support/faqs", SupportFaqListAPIView.as_view(), name="support-faqs"),
    path("support/inquiries", PublicInquiryListAPIView.as_view(), name="support-inquiries"),
    path("admin/dashboard", AdminDashboardAPIView.as_view(), name="admin-dashboard"),
    path("admin/orders", AdminOrderListAPIView.as_view(), name="admin-orders"),
    path("admin/orders/<str:order_no>", AdminOrderUpdateAPIView.as_view(), name="admin-order-update"),
    path("admin/returns", AdminReturnRequestListCreateAPIView.as_view(), name="admin-returns"),
    path("admin/returns/<int:return_request_id>", AdminReturnRequestUpdateAPIView.as_view(), name="admin-return-update"),
    path("admin/settlements", AdminSettlementListGenerateAPIView.as_view(), name="admin-settlements"),
    path("admin/settlements/<int:settlement_id>", AdminSettlementUpdateAPIView.as_view(), name="admin-settlement-update"),
    path("admin/inquiries", AdminInquiryListAPIView.as_view(), name="admin-inquiries"),
    path("admin/inquiries/<int:inquiry_id>/answer", AdminInquiryAnswerAPIView.as_view(), name="admin-inquiry-answer"),
    path("admin/support/notices", AdminSupportNoticeListCreateAPIView.as_view(), name="admin-support-notices"),
    path("admin/support/notices/<int:notice_id>", AdminSupportNoticeDetailAPIView.as_view(), name="admin-support-notice-detail"),
    path("admin/support/faqs", AdminSupportFaqListCreateAPIView.as_view(), name="admin-support-faqs"),
    path("admin/support/faqs/<int:faq_id>", AdminSupportFaqDetailAPIView.as_view(), name="admin-support-faq-detail"),
    path("admin/reviews", AdminReviewListAPIView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:review_id>", AdminReviewDeleteAPIView.as_view(), name="admin-review-delete"),
    path("admin/reviews/<int:review_id>/visibility", AdminReviewVisibilityAPIView.as_view(), name="admin-review-visibility"),
    path("admin/reviews/<int:review_id>/manage", AdminReviewManageAPIView.as_view(), name="admin-review-manage"),
    path("admin/reviews/<int:review_id>/reports", AdminReviewReportManageAPIView.as_view(), name="admin-review-reports"),
    path("admin/banners/home/manage", AdminHomeBannerListCreateAPIView.as_view(), name="admin-banner-manage"),
    path("admin/banners/home/manage/<int:banner_id>", AdminHomeBannerDetailAPIView.as_view(), name="admin-banner-detail"),
    path("admin/brand/page", AdminBrandPageSettingAPIView.as_view(), name="admin-brand-page"),
    path("admin/brand/sections", AdminBrandStorySectionListCreateAPIView.as_view(), name="admin-brand-sections"),
    path("admin/brand/sections/<int:section_id>", AdminBrandStorySectionDetailAPIView.as_view(), name="admin-brand-section-detail"),
    path("admin/products/manage/meta", AdminProductMetaAPIView.as_view(), name="admin-product-meta"),
    path("admin/products/manage", AdminProductListCreateAPIView.as_view(), name="admin-product-manage"),
    path("admin/products/manage/<int:product_id>", AdminProductDetailAPIView.as_view(), name="admin-product-detail"),
    path("admin/users/manage", AdminUserListAPIView.as_view(), name="admin-user-manage"),
    path("admin/users/manage/<int:user_id>", AdminUserDetailAPIView.as_view(), name="admin-user-detail"),
    path("admin/coupons", AdminCouponListCreateAPIView.as_view(), name="admin-coupons"),
    path("admin/coupons/<int:coupon_id>", AdminCouponDetailAPIView.as_view(), name="admin-coupon-delete"),
    path("admin/staff-users", AdminStaffUserListAPIView.as_view(), name="admin-staff-users"),
    path("admin/audit-logs", AdminAuditLogListAPIView.as_view(), name="admin-audit-logs"),
]
