# Generated by Django 5.2.11 on 2026-02-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('one_line', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('intake', models.TextField(blank=True)),
                ('target', models.TextField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('cautions', models.JSONField(blank=True, default=list)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popular_score', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetailMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_text', models.CharField(blank=True, max_length=255)),
                ('shipping_fee', models.PositiveIntegerField(default=3000)),
                ('free_shipping_threshold', models.PositiveIntegerField(default=50000)),
                ('interest_free_text', models.CharField(blank=True, max_length=255)),
                ('purchase_types', models.JSONField(blank=True, default=list)),
                ('subscription_benefit', models.CharField(blank=True, max_length=255)),
                ('options_label', models.CharField(default='상품구성', max_length=100)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('today_ship_text', models.CharField(blank=True, max_length=255)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('detail_images', models.JSONField(blank=True, default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_meta', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('HOT', 'HOT'), ('BESTSELLER', 'BESTSELLER'), ('DISCOUNT', 'DISCOUNT'), ('NEW', 'NEW'), ('RECOMMENDED', 'RECOMMENDED')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'badge_type')},
            },
        ),
    ]
