# Generated by Django 5.2.11 on 2026-02-16 12:25

import apps.common.file_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productdetailmeta',
            name='detail_images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_utils.banner_image_upload_to, validators=[apps.common.file_utils.validate_image_file]),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_utils.product_image_upload_to, validators=[apps.common.file_utils.validate_image_file]),
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.file_utils.product_detail_image_upload_to, validators=[apps.common.file_utils.validate_image_file])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('detail_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productdetailmeta')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
