# Generated by Django 5.2.11 on 2026-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_homebanner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='product',
            name='display_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping_amount',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_status',
            field=models.CharField(choices=[('TAXABLE', '과세'), ('ZERO', '영세'), ('EXEMPT', '면세')], default='TAXABLE', max_length=20),
        ),
    ]
