# Generated by Django 5.2.11 on 2026-02-20 10:58

import apps.common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_delivery_fee_product_display_end_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='ABOUT SAUSALITO', max_length=120)),
                ('hero_title', models.CharField(default='건강한 아침을 설계하는 브랜드', max_length=255)),
                ('hero_description', models.TextField(blank=True, default='우리는 복잡한 일상을 사는 사람들의 루틴에 가장 간결한 웰니스 해답을 제공합니다. 매일의 선택이 몸의 컨디션을 바꾼다고 믿습니다.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BrandStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.file_utils.banner_image_upload_to, validators=[apps.common.file_utils.validate_image_file])),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
