# Generated by Django 5.2.11 on 2026-02-16 12:25

import apps.common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.file_utils.review_image_upload_to, validators=[apps.common.file_utils.validate_image_file]),
        ),
    ]
