# Generated by Django 5.2.11 on 2026-02-21 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_admin_replied_at_review_admin_replied_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ABUSE", "ABUSE"),
                            ("ADVERTISEMENT", "ADVERTISEMENT"),
                            ("PERSONAL_INFO", "PERSONAL_INFO"),
                            ("IRRELEVANT", "IRRELEVANT"),
                            ("ETC", "ETC"),
                        ],
                        default="ETC",
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("RESOLVED", "RESOLVED"), ("REJECTED", "REJECTED")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("review", "reporter")},
            },
        ),
    ]
