# Generated by Django 5.2.11 on 2026-02-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productoption_package_fields'),
        ('orders', '0008_delete_settlementrecord'),
        ('reviews', '0004_reviewreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'order_item'), name='uniq_review_user_order_item'),
        ),
    ]
